pub const opCode = enum(u8) {
    ReturnOp,
    ConstantOp,
    NegateOp,
    AddOp,
    SubOp,
    MultOp,
    DivOp,
    EqOp,
    NeqOp,
    LessOp,
    GreatOp,
    LeqOp,
    GeqOp,
    PrintOp,
    PopOp,
    NilOp,
    DefineGlobalOp,
    GetGlobalOp,
    SetGlobalOp,
    DefineLocalOp,
    GetLocalOp,
    SetLocalOp,
    JumpIfFalseOp,
    JumpOp,
    LoopOp,

    pub fn toString(self: opCode) []const u8 {
        return switch (self) {
            .ReturnOp => "return",
            .ConstantOp => "constant",
            .NegateOp => "negate",
            .AddOp => "add",
            .SubOp => "sub",
            .MultOp => "mult",
            .DivOp => "div",
            .PrintOp => "print",
            .EqOp => "eq",
            .NeqOp => "neq",
            .LessOp => "less",
            .GreatOp => "great",
            .LeqOp => "leq",
            .GeqOp => "geq",
            .PopOp => "pop",
            .NilOp => "nilOp",
            .DefineGlobalOp => "defGlobal",
            .GetGlobalOp => "getGlobal",
            .SetGlobalOp => "setGlobal",
            .DefineLocalOp => "defLocal",
            .GetLocalOp => "getLocal",
            .SetLocalOp => "setLocal",
            .JumpIfFalseOp => "jumpIfFalse",
            .JumpOp => "jump",
            .LoopOp => "loop",
        };
    }
};
